### PR TITLE
New cmd Line claim

### PR DESCRIPTION
**Pull request by Mr-Deej**
not finished yet, still need to implement the direction check for which the line is to be claimed

### CODE REVIEW

**Comment by Mr-Deej** [comment]
p1 of #1323 i believe adding this and the fill will make it easier for them to transition to Medieval Factions

**Comment by dmccoystephenson** [comment]
To clarify, this is intended to allow a player to claim a line of chunks?

**Comment by Mr-Deej** [comment]
> To clarify, this is intended to allow a player to claim a line of chunks?

it is the start of being able to claim chunks in a line, then I was going to implement the filling of the 'shape' for what #1323 is looking for

**Comment by dmccoystephenson** [comment]
Moved these changes to the "line-claiming" branch in the parent repository.

**Pull request closed without merging**
