### PR TITLE
Moving away from the Singleton pattern.

### PR DESCRIPTION
**Pull request by dmccoystephenson**
The changes in this PR are intended to force myself to actually manage my dependencies, rather than having an over-reliance on the singleton pattern.

### CODE REVIEW

**Comment by dmccoystephenson** [comment]
Left to do:
- [ ] Deal with circular dependency between InetractionAccessChecker.java and PersistentData.java
- [ ] Refactor the commands

**Comment by dmccoystephenson** [comment]
This is a depiction of the circular dependency. Some information may be missing.
circular dependency drawio

**Comment by dmccoystephenson** [comment]
@alyphen
This is now ready for review. Let me know if you have any thoughts 👍

**Review by alyphen — APPROVED** [review]
Nice work on this, should make this project much easier to work with

**Pull request merged**
