### PR TITLE
Added Brazilian Portuguese (pt-BR) translation for Faction-Medieval p…

### PR DESCRIPTION
**Pull request by MestreWilll**
I've added a Brazilian Portuguese (pt-BR) translation for the Faction-Medieval plugin. The translation is contained in a new file within the language folder to support Portuguese-speaking users.

I believe this translation will help expand the user base of the plugin to those who prefer or need to play in Portuguese. Please review the changes, and let me know if there are any modifications or improvements needed.

Thank you for considering this contribution!

Best regards,
MestreWilll

### CODE REVIEW

**Comment by alyphen** [comment]
Hi! Thanks for your work on this and your interest in sharing Medieval Factions with Brazilian Portuguese players!

Including translations in the main project is difficult, not because of the initial translation effort, but because by including a translation, we commit to maintaining it into the future, including all updates that may add additional functionality.
This increases the effort required to release new features, and means we spend time chasing translators who may have gone inactive since, or trying to find new speakers of the language. All in all, this means it's not something we like to do often.

I'd suggest you share your translation independently of the main Medieval Factions project, and update it after each new update comes out. This allows us to iterate quickly, and also makes the project accessible to Brazilian Portuguese speakers. Any translation files in the configuration folder will be recognised and can be set as a language in the main config.

@dmccoystephenson may have different opinions on this to me, so I'm open for a discussion.

We have spoken internally about building some functionality to allow downloading additional translations from in-game, but this has not come to fruition at this time.

**Comment by Unix-User** [comment]
Ola, estou usando essa tradução em meu servidor, e me parece que a tradução esta muito boa com exceção de alguns bugs que planejo rastrear e corrigir em breve, obrigado pelo compartilhamento

**Review by dmccoystephenson — APPROVED** [review]
I support including this translation in the project. We can use online tools to translate messages and members of the community can correct any mistakes directly via contributing to the source code.

**Comment by dmccoystephenson** [comment]
Modified base branch to `develop`

**Review by dmccoystephenson — APPROVED** [review]
Thank you for your contribution, @MestreWilll!

**Pull request merged**
